### ISSUE TITLE
binoculars showing same fish on every fishing spot

### ISSUE THREAD

**Issue by kuma51** [xen-42/DredgeVR#65]
unfortunately the binoculars show the same fish with the mod on all fishing spots. without the mod the bug is not there. so it must come from the mod. i have already uninstalled and reinstalled everything and also started a new savegame. unfortunately all to no avail.

**Comment by xen-42** [comment]
Thank you for the bug report, this is likely an issue caused by the game update yesterday, I'll get on it

**Comment by xen-42** [comment]
Fixed this main issue, found some other new bugs though that I'll track here: https://github.com/xen-42/DredgeVR/issues/68
